# -*- coding: utf-8 -*-
"""Submission 1 - NLP - BPML - Hazmi Cokro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W3pbif2wBi7GVgTHqa6Ch1G90FUtzeE6

Mochammad Hazmi Cokro Mandiri
> Dataset : "Movie Genre Data" \
> Sumber : Kaggle \
> Link Dataset : https://www.kaggle.com/lokkagle/movie-genre-data

Library
"""

from google.colab import drive

# u/ dataframe
import pandas as pd
import re


# u/ split data
from sklearn.model_selection import train_test_split

# u/ preprocessing dan layer
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

# u/ visualisasi plot
import matplotlib.pyplot as plt

"""Mount ke drive"""

drive.mount('/content/drive/')

"""Read Dataset dari drive"""

df = pd.read_csv("/content/drive/My Drive/Submission1/kaggle_movie_train.csv")
df.head()

"""Mengecek jumlah value tiap genre"""

df['genre'].value_counts()

"""Kesempatan kali ini akan menggunakan 4 genre saja yaitu comedy action sci-fi dan horror"""

# Menghapus genre selain 4 genre tersebut
df = df[~df['genre'].isin(['drama','thriller','other','adventure','romance'])]
df['genre'].value_counts()

"""Preprocessing kolom text"""

# Menghapus special character di kolom text
df['Text'] = df['text'].map(lambda x: re.sub(r'\W+', ' ', x))
# drop kolom id dan text lama
df = df.drop(['id', 'text'], axis=1)
df.head()

"""Pengecekan nilai kosong"""

# Mengecek nilai kosong / nan
# Jika true maka ada dan jika false maka tidak ada nilai kosong / nan
df.isnull().values.any()

"""Pelabelan genre"""

genre = pd.get_dummies(df.genre)
df_genre = pd.concat([df, genre], axis=1)
df_genre = df_genre.drop(columns='genre')
df_genre.head()

"""Mengubah tipe data"""

# Mengubah tipe data menjadi str dan numpy array 
text = df_genre['Text'].astype(str)
label = df_genre[['action', 'comedy','horror','sci-fi']].values

"""Split dataset 20% test / validasi"""

genre_train, genre_test, label_train, label_test = train_test_split(text, label, test_size = 0.2)

"""Penggunaan tokenizer"""

# mengkonversikan ke sequence
tokenizer = Tokenizer(num_words=5000, oov_token='x')
tokenizer.fit_on_texts(genre_train) 
tokenizer.fit_on_texts(genre_test)
 
sekuens_train = tokenizer.texts_to_sequences(genre_train)
sekuens_test = tokenizer.texts_to_sequences(genre_test)
 
padded_train = pad_sequences(sekuens_train) 
padded_test = pad_sequences(sekuens_test)

"""Pemodelan Sequential dengan Embedding dan LSTM"""

model = Sequential([
    Embedding(input_dim=5000, output_dim=16),
    LSTM(64),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(4, activation='softmax')
])

"""Model compiile dengan optimizer Adam"""

Adam(learning_rate=0.00146, name='Adam')
model.compile(optimizer = 'Adam',loss = 'categorical_crossentropy',metrics = ['accuracy'])

"""Penggunaan callback u/ accuracy dan val diatas 90%"""

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')>0.9 and logs.get('val_accuracy')>0.9):
      print("\nAkurasi train dan validasi didapat telah mencapai nilai > 90%!")
      self.model.stop_training = True
callbacks = myCallback()

"""Melatih model"""

num_epochs = 30
history = model.fit(padded_train, label_train, epochs=num_epochs, validation_data=(padded_test, label_test), verbose=2, callbacks=[callbacks])

"""Membuat plot accuracy dan loss"""

# Plot Accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Akurasi Model')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

# Plot Loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Loss Model')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()